version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db

    ports:
      - '27017:27017'
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redis:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    depends_on:
      - mongo
      - redis
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - app-network
    environment:
      APP_PORT: ${APP_PORT}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}

volumes:
  mongo:
  redis:

networks:
  app-network:
    driver: bridge
